name: AFKLoot
version: '1.19.4'
main: online.alibabji.afkloot.AFKLoot
api-version: 1.19
author: Alibabji
description: makes players able to access disconnected player's inventory (Inpired by Heptagram)